version: '3'
services:
    mariadb:
        restart: unless-stopped
        image: 'mariadb:10'
        ports:
            - '127.0.0.1:3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'mariadb:/var/lib/mysql'
            - './mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        networks:
            - network
    web:
        build:
            target: dev
        volumes:
            - './web:/usr/src/app'
        tmpfs: /tmp
        ports:
            - '5173:5173'
    api:
        build:
            target: dev
        volumes:
            - './api:/usr/src/app'
        depends_on:
            - mariadb
            - redis

volumes:
    mariadb:
        driver: local