version: '3'
services:
    db:
        image: postgres:15.3-alpine
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - '5432:5432'
        networks:
            - network
        volumes: 
            - db:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/setup.sql
    redis:
        image: redis:7.0-bullseye
        restart: always
        ports:
            - '6379:6379'
        networks:
            - network
        command: redis-server --loglevel warning
networks:
    network:
        driver: bridge
volumes:
    db:
        driver: local
