version: '3'
services:
    mariadb:
        restart: unless-stopped
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'mariadb:/var/lib/mysql'
            - './mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        networks:
            - network
    redis:
        image: redis:7.0-bullseye
        restart: always
        ports:
            - '6379:6379'
        networks:
            - network
        command: redis-server --loglevel warning
networks:
    network:
        driver: bridge
volumes:
    mariadb:
        driver: local
